# Site settings
title: MyGGLytics
email: max.vassal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
  Hey there! You are most welcome here. This is a website I use to help my Google Analytics learning.
  Here I will chit-chat about web dev and learn some more about static
  website.
  "blank"
  Edit this  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: maxvassal
github_username:  maxvassal

# Build settings
markdown: kramdown
