# Site settings
title: MyGGLytics
email: max.vassal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey there! You are most welcome here. This is a website I made to 
  apply what I learn during my Google Analytics learning.
  Here I will chit-chat about non sense and learn some more about static
  website and how to improve my skills as a "ingénieur du numériqueé.
  Have a great time if you can. :)
  edit this  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: maxvassal
github_username:  maxvassal

# Build settings
markdown: kramdown
